### ISSUE TITLE
Implement {comment} tag

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#1]
Implement the existing tag used in the CSFG. The function is found within [`markdownsection.py`](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py).

```
[comment]
    regex: ^(\n*\{comment([^}]+\}|\}[\S\s]+?comment end\})\n*)+
    function: delete_comment
```

**Comment by hayleyavw** [comment]
https://github.com/uccser/kordac/commit/f5faa6683ec8bbc56ef3770d1e0ec34b00687234

**Comment by hayleyavw** [comment]
For files with multiple comments, we should be counting the number of matches it gets

**Comment by JackMorganNZ** [comment]
Is this for testing purposes? Or for statistics?

**Comment by hayleyavw** [comment]
Testing purposes.
A test file could contain 6 comment blocks, maybe we should check that it matched all 6.
