### ISSUE TITLE
Add code style checker for consistency within project

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#107]
As this project now has multiple authors (all with different programming backgrounds), it would be worth adding a style checker to promote readable code.

Code Climate (https://codeclimate.com/) is system that I used in the past and was very useful. It has PEP8 support built in.

**Comment by ravenmaster001** [comment]
@JackMorganNZ So I think I accidentally already added this???.... I'm not too sure how it integrates with Github though.

**Comment by JackMorganNZ** [comment]
I don't think you have added this? What did you add?

I was suggesting some combination of the following:

- Add the `PEP8` Python package and add it's tests to the existing test suite.
- Code Climate for style checks https://github.com/integrations/code-climate
- Hound for simplier checks of PR styles (don't think this gives status of overall project though).
- Codecov https://github.com/integrations/codecov or  Coveralls https://github.com/integrations/coveralls for checking coverage of test cases

All GitHub integrations are available here: https://github.com/integrations The checker doesn't have to integrate with GitHub, but it's a nice to have.
