### ISSUE TITLE
Implement {panel} tag

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#14]
Implement the existing tag used in the CSFG. The function is found within [`markdownsection.py`](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py).

```
[panel]
    regex: ^\{panel ?(?P<args>[^\}]*)\}(?P<content>[\s\S]*?)\{panel end\}
    function: create_panel
```

**Comment by ravenmaster001** [comment]
@hayleyavw @JackMorganNZ Who's job is it to deal with teacher-note types? Would this be before or after kordac.

**Comment by hayleyavw** [comment]
This will be dealt with after kordac, there might be some django specific syntax to output along with the rest of the html, but we wont know what this will look like until the conditional tag has been implemented ( #3 ).

**Comment by ravenmaster001** [comment]
Many test module fixes due to the refactor in develop. These need to be consider when merging back into develop. See commit 02d49c47c8aa0ab57c8db99f0cf4c8f51c7f4f94

**Comment by hayleyavw** [comment]
@ravenmaster001 no guidelines for this case, please invent some and let us know what you decided on/why :)

**Comment by ravenmaster001** [comment]
@hayleyavw Looks like we should have preprocessors for what I want to do and those tests should be moved to test the preprocessors. This means in our processors and their tests that we can assume the markdown is well-formed. @JackMorganNZ Should we add an issue for this and put it at the back of the backlog or should I focus on this now?

**Comment by ravenmaster001** [comment]
As per our discussion an exception will be created and bring kordac to a grinding halt.
