### ISSUE TITLE
Add Restructured Text syntax checker

### ISSUE THREAD

**Issue by hayleyavw** [uccser/kordac#142]
https://github.com/myint/rstcheck

**Comment by ravenmaster001** [comment]
I assume you are already working on this @hayleyavw

**Comment by hayleyavw** [comment]
yea will be adding it over the next couple days, going to add it to the CSU so figured I'll do both at once

**Comment by hayleyavw** [comment]
rstcheck has inconsistent behaviour across operating systems...seems unreliable, so dropping this suggestion.
