### ISSUE TITLE
Load html templates from file

### ISSUE THREAD

**Issue by hayleyavw** [uccser/kordac#17]
Currently each tag has a html string defined in it's processor file, these should be retrieved from a template file instead.

**Comment by hayleyavw** [comment]
Commit https://github.com/uccser/kordac/commit/5b010edf0979b464c5d58bf96901b97a5b1e3e75 has most tags restructured.

Interactive and headings will be converted once there are tests in place for them first.

**Comment by ravenmaster001** [comment]
@hayleyavw Is this issue not finished, can we close this. Tags can handle adding their own html-template files can be handed by the appropriate tag issue.
