### ISSUE TITLE
Choose production name

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#19]

**Comment by JackMorganNZ** [comment]
Possible Maori suggestion: **Panoni**

1. (verb) to change the form or structure of
2. (noun) change

[maoridictionary.co.nz](http://maoridictionary.co.nz/search?idiom=&phrase=&proverb=&loan=&histLoanWords=&keywords=panoni)

**Comment by hayleyavw** [comment]
In the process of asking local iwi for input on this.

**Comment by hayleyavw** [comment]
"Verto" - see #150
