### ISSUE TITLE
Implement {version-specific} tag

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#2]
Implement the existing tag used in the CSFG. The function is found within [`markdownsection.py`](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py).

```
[version-specific]
    regex: ^\{version-specific-content ?(?P<args>[^\}]*)\}(?P<content>[\s\S]*?)\{version-specific-content end\}
    function: check_version_specific_content
```

This conditionally removed content when creating files for static site generation. However the Django system should now perform the logic if this content should be displayed.

**Comment by ravenmaster001** [comment]
This will be handled by the conditional tag in issue #3.
