### ISSUE TITLE
Remove run.py file

### ISSUE THREAD

**Issue by hayleyavw** [uccser/kordac#22]
This file exists just to run the extension on a couple markdown files to check for python errors. Once the test suite is complete, this should be removed since the tests can give all the output we need.

**Comment by hayleyavw** [comment]
The example chapters should also be removed.

**Comment by hayleyavw** [comment]
I will begrudgingly rename this. Yes, it will be deleted eventually.

**Comment by ravenmaster001** [comment]
This is handled by issue #51
