### ISSUE TITLE
Kordac should return more than HTML

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#29]
**Ideally** Kordac would return an object that would contain the following properties:

- Generated HTML
- First heading of page #28
- Required files #7 #11 
- Dictionary for glossary #12 

**However** Kordac doesn't return anything, the Markdown parser returns the converted HTML. However if  a reference to Kordac is saved, we could extract these saved values after each conversion. However, we need to make sure we don't retain information from previous conversions.

**Comment by hayleyavw** [comment]
(I knew I had written this somewhere! found it on the whiteboard this morning!)
Not sure if I understand your thinking there @JackMorganNZ or not, just to confirm: Kordac would return an object, giving a user functionality like:
```
my_converted_file = Kordac(my_unconverted_file)
print(my_converted_file.heading)
my_function_to_check_for_required_files(my_converted_file.required_files)
```
right? Then it would behave like any other object in python, creating `another_converted_file = Kordac(here_is_a_file)` would not have any issues with using information from a previous conversion?

**Comment by JackMorganNZ** [comment]
The issue I see is that we are never called Kordac like: 

```
Kordac()
```

It's more like:

```
kordac = Kordac()
markdown.markdown(text, extensions=[kordac]))
```

The function that's actually called is `markdown.markdown()`

**Comment by hayleyavw** [comment]
ahhh gotcha. Ok well we could write a wrapper for this? At the moment we have `run.py` which is just our quick way of testing things, but there's no reason why we couldn't actually turn this into something functional. Or do we want to stick with what you've just described?
We could have another class that has `run()` as  a function, and the user passes in their string, and this new class returns an an object with all the data we need/listed above. This could give the user the choice to use just the `Kordac` extension, or to use our wrapper to output a very specific object.

**Comment by JackMorganNZ** [comment]
This would work, though we would need to be clear in the documentation about the two different usages. Using a wrapper would work, though you would have to pass the wrapper the non-Kordac extensions you wish `markdown` to be run with. It would work, but seems a tad ungraceful.

Another option I thought of would be to extract the the information from Kordac:

```
kordac = Kordac()
html = markdown.markdown(markdown_string, extensions=[math, kordac, etc]))
file_properties = kordac.lastFileProperties()
all_required_files.add(file_properties.required_files)
```

This would accomplish the same purpose but is also a tad ungraceful.

Out of the two options, the first one sounds more promising though possibly harder to implement as we would need to re-implement function hooks for all the `markdown` functions. Need to try implementing it see how it would function.

**Comment by hayleyavw** [comment]
I think I like the option of giving the user two different ways to use it, it's a little bit more intuitive and makes Kordac a little more versatile. Not big on the idea of Kordac remembering things from it's last run.
Would we need function hooks for all that markdown has to offer, only the few we use, because if someone would like more, there is nothing stopping them from forking this repo...but this does seem terrible. Never written function hooks before, no idea how easy/hard that would be ¯\_(ツ)_/¯

**Comment by hayleyavw** [comment]
Commit https://github.com/uccser/kordac/commit/7e3ba6d639b4df585bae8d8589a6e0194f224f16 is relevant to this issue.
There is now an additional class created that returns an object with the required attributes (only `html_string` is actually processed, both `heading` and `required_files` currently return default values, the glossary has not been considered yet.)
There is a new `run.py` file, for use while Kordac is under development, which calls this new class.
Usage:
```
converted = Kordac.run(md_string)
html_string = converted.html_string
```
