### ISSUE TITLE
Load custom template files

### ISSUE THREAD

**Issue by hayleyavw** [uccser/kordac#31]
Kordac should load custom template files specified by the user (CSUnplugged and CSFieldGuide will have different html templates)
Relevant to issue #17

**Comment by hayleyavw** [comment]
All templates are loaded with the default templates specified with the `html-templates/` folder in Kordac, **unless they are specified by the user**
Usage:
```
template_dict = {
    'panel': '<div class="panel">{content}</div>'
}
converter = kordac.Kordac()
result = converter.run(s, tags=[], html_templates=template_dict)
```
In this example, the panel template will be as specified in the dictionary, all other templates are loaded from `html-templates/` as usual.

**Comment by JackMorganNZ** [comment]
Excellent, this is exactly how I would expect to use it. 

We should include test cases where the provided string is given over multiple lines.

**Comment by hayleyavw** [comment]
@JackMorganNZ cool, in that case I will close the issue. Implementing this feature does mean that the test suite is going to suddenly have a lot more to test, this will be considered when the test suite gets an overhaul in the next couple weeks.
