### ISSUE TITLE
Implement rendering of math

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#4]
Implement the rendering of math, based off tags used in the CSFG. The function is found within [`markdownsection.py`](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py).

```
[maths]
    regex: \{(?P<type>math|math-block)\}(?P<equation>[\s\S]+?)\{(math|math-block) end\}
    function: process_math_text
```

However the module we are extending off may have math processing built in or available as an extension. If math processing exists that uses the standard LaTeX math delimiters, then we can switch from using `{math}` and `{math-block}` tags to using the standard LaTeX math delimiters in our projects.

**Comment by ravenmaster001** [comment]
As in the [docs](http://kordac.readthedocs.io/en/issue-38/useful-extensions.html) the [mdx_math](https://github.com/mitya57/python-markdown-math) module supports LaTeX math delimiters. We need to consider whether we want to use the `render_to_span` modifier for javascript disabled environments.
