### ISSUE TITLE
Implement {codeblock} tag

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/kordac#41]
Implement the existing tag used in the CSFG. The function is found within [markdownsection.py](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py)
```
[code block]
    regex: ^```(?P<language>[^\n]*)\n(?P<code>[^`]*)```
    function: process_code_block
```

**Comment by hayleyavw** [comment]
copy of #15 :P pick one to keep and one to close and please remove the v1.0.0 milestone from the issue before closing.
