### ISSUE TITLE
Move regex's to different file format

### ISSUE THREAD

**Issue by hayleyavw** [uccser/kordac#42]
#20 using the json format means that we can't use the raw-string prefix, another format considered is YAML,  but as mentioned (here)[https://github.com/tobie/ua-parser/issues/117] YAML may be much slower to load. Not sure that this will be a problem though since we have a very finite number of regex's to load, and they are only loaded once.

**Comment by ravenmaster001** [comment]
We have decided that `JSON` is not a terrible format for storing our static processor information.
