### ISSUE TITLE
Update Test Suite to support Jinja templates

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/kordac#49]
Essentially update each current class to Mock out the Jinja templates similar to the html templates. Notifying @hayleyavw

**Comment by hayleyavw** [comment]
And need to add so many more cases since some tags can be left empty

**Comment by hayleyavw** [comment]
And also some parameters are required - need to implement this.

**Comment by ravenmaster001** [comment]
Closing issue, most of the rest of the work should be handled by the appropriate tag issues.
