### ISSUE TITLE
Implement {video} tag

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#8]
Implement the existing tag used in the CSFG. The function is found within [`markdownsection.py`](https://github.com/uccser/cs-field-guide/blob/develop/generator/markdownsection.py).

```
[video]
    regex: ^\{video (?P<args>[^\}]*)\}
    function: create_video_html
```

**Comment by ravenmaster001** [comment]
@hayleyavw  should this be closed? (Is Github still not closing issues properly *sigh*)

**Comment by JackMorganNZ** [comment]
It will only close if the word `fixes` or `fix` is before the issue number (https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by ravenmaster001** [comment]
@JackMorganNZ I have had a few issues not actually close recently when doing that. (Ensuring fixes was both in the title and message on the Github PR merge tool.)

**Comment by JackMorganNZ** [comment]
Odd, send me an example when you encounter one and I'll look into it.
