### ISSUE TITLE
Change tag parameter labels to be consistent with either dashes or underscore separators

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#85]

**Comment by ravenmaster001** [comment]
@JackMorganNZ For `Jinja` they have to be underscores.

**Comment by JackMorganNZ** [comment]
This is referring to the labels used by authors, and I think 99% of them use dashes (`{boxed-text}`, etc), but I have accidentally implemented a few underscores. The dashes names of tags and it's parameters match the processor labels too.

The Jinja2 HTML placeholders should always be underscores like you said, but these aren't exposed to authors, just developers.

**Comment by ravenmaster001** [comment]
This was fixed by pull request #91
