### ISSUE TITLE
Developer Docs Page - Overview

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/kordac#94]

**Comment by hayleyavw** [comment]
Things docs need to include:
- Intro to codebase (folder structure, OOP explanation/overview)
- How to make a new processor
- How to run test suite
- Contributing - style guide, issue making

**Comment by ravenmaster001** [comment]
@JackMorganNZ  yet again fixes does not work.

**Comment by JackMorganNZ** [comment]
No idea sorry, check GitHub support? I've never had issues. Maybe it's a thing when merging from GitHub issue page?
